/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/settings/About.vue')['default']
    Appearance: typeof import('./src/components/settings/Appearance.vue')['default']
    ArrayInput: typeof import('./src/components/ArrayInput.vue')['default']
    ArraySelect: typeof import('./src/components/ArraySelect.vue')['default']
    AuditLogTab: typeof import('./src/components/AuditLogTab.vue')['default']
    BackupTab: typeof import('./src/components/BackupTab.vue')['default']
    BDropdown: typeof import('bootstrap-vue-next')['BDropdown']
    BDropdownItem: typeof import('bootstrap-vue-next')['BDropdownItem']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    Confirm: typeof import('./src/components/Confirm.vue')['default']
    Container: typeof import('./src/components/Container.vue')['default']
    General: typeof import('./src/components/settings/General.vue')['default']
    GlobalEnv: typeof import('./src/components/settings/GlobalEnv.vue')['default']
    HiddenInput: typeof import('./src/components/HiddenInput.vue')['default']
    HomelabCapacityTab: typeof import('./src/components/HomelabCapacityTab.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    MonitoringTab: typeof import('./src/components/MonitoringTab.vue')['default']
    NetworkInput: typeof import('./src/components/NetworkInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Security: typeof import('./src/components/settings/Security.vue')['default']
    StackList: typeof import('./src/components/StackList.vue')['default']
    StackListItem: typeof import('./src/components/StackListItem.vue')['default']
    StackStatsBadge: typeof import('./src/components/StackStatsBadge.vue')['default']
    StackUpdateBadge: typeof import('./src/components/StackUpdateBadge.vue')['default']
    Terminal: typeof import('./src/components/Terminal.vue')['default']
    TwoFADialog: typeof import('./src/components/TwoFADialog.vue')['default']
    Uptime: typeof import('./src/components/Uptime.vue')['default']
    WatcherSettings: typeof import('./src/components/WatcherSettings.vue')['default']
  }
}
