services:
  dockge:
    image: ghcr.io/aerya/dockge-enhanced:latest
    container_name: dockge-enhanced
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - /opt/stacks:/opt/stacks
      - /backup:/backup          # optionnel — volume dédié au backup local Restic
    environment:
      - DOCKGE_STACKS_DIR=/opt/stacks
      - DOCKGE_DATA_DIR=/app/data
      - DOCKER_API_VERSION=x.xx  # optionnel — pour certains NAS où Docker ne supporte pas d'API récente
      - TZ=Europe/Paris
