import * as fs from "fs/promises";
import * as path from "path";
import childProcessAsync from "promisify-child-process";

interface DockerOptions { cwd?: string }

async function docker(args: string[], options: DockerOptions = {}): Promise<string> {
    const result = await childProcessAsync.spawn("docker", args, { encoding: "utf8",
        ...options });
    if ((result.code ?? 0) !== 0) {
        throw new Error(result.stderr?.toString() || `docker ${args[0]} failed`);
    }
    return result.stdout?.toString() ?? "";
}

const DATA_DIR = process.env.DOCKGE_DATA_DIR ?? "/opt/dockge/data";
const STACKS_DIR = process.env.DOCKGE_STACKS_DIR ?? "/opt/stacks";
const SETTINGS_PATH = path.join(DATA_DIR, "dozzle-settings.json");

export const DOZZLE_STACK_NAME = "dozzle-dockge-enhanced";
export const DOZZLE_CONTAINER_NAME = "dozzle-dockge-enhanced";
export const DOZZLE_IMAGE = "amir20/dozzle:latest";
const DOZZLE_STACK_DIR = path.join(STACKS_DIR, DOZZLE_STACK_NAME);
const DOZZLE_COMPOSE_FILE = "compose.yaml";

export interface DozzleSettings {
    enabled: boolean;
    port: number;
    customUrl: string;
}

export type DozzleStatus = "running" | "stopped" | "error";

interface ContainerInspect {
    Config?: { Image?: string; Labels?: Record<string, string> };
    HostConfig?: {
        PortBindings?: Record<string, Array<{ HostPort?: string }> | null>;
        RestartPolicy?: { Name?: string };
    };
    Mounts?: Array<{
        Type?: string;
        Name?: string;
        Source?: string;
        Destination?: string;
        RW?: boolean;
    }>;
}

const DEFAULT_SETTINGS: DozzleSettings = { enabled: false,
    port: 8080,
    customUrl: "" };

export function buildDozzleCompose(port: number): string {
    return [
        "# Generated by Dockge-Enhanced — managed Dozzle service",
        `name: ${DOZZLE_STACK_NAME}`,
        "services:",
        "  dozzle:",
        `    image: ${DOZZLE_IMAGE}`,
        `    container_name: ${DOZZLE_CONTAINER_NAME}`,
        "    restart: unless-stopped",
        "    ports:",
        `      - "${port}:8080"`,
        "    volumes:",
        "      - /var/run/docker.sock:/var/run/docker.sock:ro",
        "      - dozzle_dockge_data:/data",
        "volumes:",
        "  dozzle_dockge_data:",
        "    name: dozzle_dockge_data",
        "",
    ].join("\n");
}

export function isManagedComposeContainer(container: ContainerInspect): boolean {
    const labels = container.Config?.Labels ?? {};
    return labels["com.docker.compose.project"] === DOZZLE_STACK_NAME &&
        labels["com.docker.compose.service"] === "dozzle";
}

export function isLegacyManagedDozzle(container: ContainerInspect, port: number): boolean {
    if (container.Config?.Image !== DOZZLE_IMAGE || isManagedComposeContainer(container)) {
        return false;
    }

    const mounts = container.Mounts ?? [];
    const socketMount = mounts.some((mount) =>
        mount.Type === "bind" && mount.Source === "/var/run/docker.sock" &&
        mount.Destination === "/var/run/docker.sock" && mount.RW === false,
    );
    const dataMount = mounts.some((mount) =>
        mount.Type === "volume" && mount.Name === "dozzle_dockge_data" && mount.Destination === "/data",
    );
    const portBindings = container.HostConfig?.PortBindings?.["8080/tcp"] ?? [];
    const expectedPort = portBindings.some((binding) => binding.HostPort === String(port));
    const restartPolicy = container.HostConfig?.RestartPolicy?.Name === "unless-stopped";
    return socketMount && dataMount && expectedPort && restartPolicy;
}

export class DozzleManager {
    private static _instance: DozzleManager;
    settings: DozzleSettings = { ...DEFAULT_SETTINGS };
    private _starting = false;

    static getInstance(): DozzleManager {
        if (!DozzleManager._instance) {
            DozzleManager._instance = new DozzleManager();
        }
        return DozzleManager._instance;
    }

    async loadSettings(): Promise<void> {
        try {
            const raw = await fs.readFile(SETTINGS_PATH, "utf8");
            this.settings = { ...DEFAULT_SETTINGS,
                ...JSON.parse(raw) as Partial<DozzleSettings> };
        } catch {
            this.settings = { ...DEFAULT_SETTINGS };
        }
    }

    async saveSettings(partial: Partial<DozzleSettings>): Promise<void> {
        const port = Number(partial.port ?? this.settings.port);
        if (!Number.isInteger(port) || port < 1024 || port > 65535) {
            throw new Error("Invalid Dozzle port");
        }
        this.settings = { ...this.settings,
            ...partial,
            port };
        await fs.mkdir(DATA_DIR, { recursive: true });
        await fs.writeFile(SETTINGS_PATH, JSON.stringify(this.settings, null, 2));
        if (this.settings.enabled) {
            await this.start();
        } else {
            await this.stop();
            await fs.rm(DOZZLE_STACK_DIR, { recursive: true,
                force: true });
        }
    }

    getSettingsSafe(): DozzleSettings {
        return { ...this.settings };
    }

    private composeArgs(args: string[]): string[] {
        return [ "compose", "--project-name", DOZZLE_STACK_NAME, "--file", DOZZLE_COMPOSE_FILE, ...args ];
    }

    private async writeComposeFile(): Promise<void> {
        await fs.mkdir(DOZZLE_STACK_DIR, { recursive: true });
        await fs.writeFile(path.join(DOZZLE_STACK_DIR, DOZZLE_COMPOSE_FILE), buildDozzleCompose(this.settings.port), "utf8");
    }

    private async inspectExistingContainer(): Promise<ContainerInspect | null> {
        try {
            const stdout = await docker([ "inspect", DOZZLE_CONTAINER_NAME ]);
            return (JSON.parse(stdout) as ContainerInspect[])[0] ?? null;
        } catch {
            return null;
        }
    }

    private async migrateLegacyContainer(): Promise<void> {
        const existing = await this.inspectExistingContainer();
        if (!existing || isManagedComposeContainer(existing)) {
            return;
        }
        if (!isLegacyManagedDozzle(existing, this.settings.port)) {
            throw new Error(`Le conteneur ${DOZZLE_CONTAINER_NAME} existe mais n’appartient pas à Dockge-Enhanced`);
        }
        console.log("[DozzleManager] Migration du conteneur historique vers Docker Compose");
        await docker([ "stop", DOZZLE_CONTAINER_NAME ]);
        await docker([ "rm", DOZZLE_CONTAINER_NAME ]);
    }

    async startIfEnabled(): Promise<void> {
        await this.loadSettings();
        if (this.settings.enabled) {
            await this.start();
        }
    }

    async start(): Promise<void> {
        if (this._starting) {
            return;
        }
        this._starting = true;
        try {
            await this.writeComposeFile();
            await this.migrateLegacyContainer();
            await docker(this.composeArgs([ "up", "-d", "dozzle" ]), { cwd: DOZZLE_STACK_DIR });
        } finally {
            this._starting = false;
        }
    }

    async stop(): Promise<void> {
        try {
            const existing = await this.inspectExistingContainer();
            if (existing && isManagedComposeContainer(existing)) {
                await docker(this.composeArgs([ "down" ]), { cwd: DOZZLE_STACK_DIR });
            } else if (existing && isLegacyManagedDozzle(existing, this.settings.port)) {
                await docker([ "stop", DOZZLE_CONTAINER_NAME ]);
                await docker([ "rm", DOZZLE_CONTAINER_NAME ]);
            }
        } catch {
            // Conteneur absent : normal.
        }
    }

    async getStatus(): Promise<DozzleStatus> {
        try {
            const stdout = await docker([ "inspect", "--format", "{{.State.Running}}", DOZZLE_CONTAINER_NAME ]);
            return stdout.trim() === "true" ? "running" : "stopped";
        } catch {
            return "stopped";
        }
    }
}
