import * as fs from "fs/promises";
import * as path from "path";
import childProcessAsync from "promisify-child-process";

async function docker(args: string[]): Promise<string> {
    const result = await childProcessAsync.spawn("docker", args, { encoding: "utf8" });
    if ((result.code ?? 0) !== 0) {
        throw new Error(result.stderr?.toString() || `docker ${args[0]} failed`);
    }
    return result.stdout?.toString() ?? "";
}
const DATA_DIR = process.env.DOCKGE_DATA_DIR ?? "/opt/dockge/data";
const STACKS_DIR = process.env.DOCKGE_STACKS_DIR ?? "/opt/stacks";
const SETTINGS_PATH = path.join(DATA_DIR, "dozzle-settings.json");

export const DOZZLE_STACK_NAME = "dozzle-dockge-enhanced";
export const DOZZLE_CONTAINER_NAME = "dozzle-dockge-enhanced";
export const DOZZLE_IMAGE = "amir20/dozzle:latest";
const DOZZLE_STACK_DIR = path.join(STACKS_DIR, DOZZLE_STACK_NAME);

export interface DozzleSettings {
    enabled: boolean;
    port: number;
    customUrl: string;
}

export type DozzleStatus = "running" | "stopped" | "error";

const DEFAULT_SETTINGS: DozzleSettings = {
    enabled: false,
    port: 8080,
    customUrl: "",
};

export class DozzleManager {
    private static _instance: DozzleManager;
    settings: DozzleSettings = { ...DEFAULT_SETTINGS };
    private _starting = false;

    static getInstance(): DozzleManager {
        if (!DozzleManager._instance) {
            DozzleManager._instance = new DozzleManager();
        }
        return DozzleManager._instance;
    }

    async loadSettings(): Promise<void> {
        try {
            const raw = await fs.readFile(SETTINGS_PATH, "utf8");
            this.settings = { ...DEFAULT_SETTINGS,
                ...JSON.parse(raw) as Partial<DozzleSettings> };
        } catch {
            this.settings = { ...DEFAULT_SETTINGS };
        }
    }

    async saveSettings(partial: Partial<DozzleSettings>): Promise<void> {
        const port = Number(partial.port ?? this.settings.port);
        if (!Number.isInteger(port) || port < 1024 || port > 65535) {
            throw new Error("Invalid Dozzle port");
        }
        this.settings = { ...this.settings,
            ...partial,
            port };
        await fs.mkdir(DATA_DIR, { recursive: true });
        await fs.writeFile(SETTINGS_PATH, JSON.stringify(this.settings, null, 2));
        if (this.settings.enabled) {
            await this.start();
        } else {
            await this.stop();
            await fs.rm(DOZZLE_STACK_DIR, { recursive: true,
                force: true });
        }
    }

    getSettingsSafe(): DozzleSettings {
        return { ...this.settings };
    }

    private async writeComposeFile(): Promise<void> {
        await fs.mkdir(DOZZLE_STACK_DIR, { recursive: true });
        await fs.writeFile(path.join(DOZZLE_STACK_DIR, "compose.yaml"), [
            "# Generated by Dockge-Enhanced — managed Dozzle service",
            "services:",
            "  dozzle:",
            `    image: ${DOZZLE_IMAGE}`,
            `    container_name: ${DOZZLE_CONTAINER_NAME}`,
            "",
        ].join("\n"), "utf8");
    }

    async startIfEnabled(): Promise<void> {
        await this.loadSettings();
        if (this.settings.enabled) {
            await this.start();
        }
    }

    async start(): Promise<void> {
        if (this._starting) {
            return;
        }
        this._starting = true;
        try {
            await this.stop();
            await this.writeComposeFile();
            await docker([
                "run", "-d",
                "--name", DOZZLE_CONTAINER_NAME,
                "-p", `${this.settings.port}:8080`,
                "-v", "/var/run/docker.sock:/var/run/docker.sock:ro",
                "-v", "dozzle_dockge_data:/data",
                "--restart", "unless-stopped",
                DOZZLE_IMAGE,
            ]);
        } finally {
            this._starting = false;
        }
    }

    async stop(): Promise<void> {
        try {
            await docker([ "stop", DOZZLE_CONTAINER_NAME ]);
            await docker([ "rm", DOZZLE_CONTAINER_NAME ]);
        } catch { /* absent: normal */ }
    }

    async getStatus(): Promise<DozzleStatus> {
        try {
            const stdout = await docker([ "inspect", "--format", "{{.State.Running}}", DOZZLE_CONTAINER_NAME ]);
            return stdout.trim() === "true" ? "running" : "stopped";
        } catch {
            return "stopped";
        }
    }
}
